### ISSUE TITLE
[Bug]: build errors occur on Ruby 3.4.8 or later when `gem install rfmt`

### ISSUE THREAD

**Issue by hachi8833** [fs0414/rfmt#70]
### rfmt version

1.4.1

### Ruby version

ruby 3.4.8 (2025-12-17 revision 995b59f666) +YJIT +PRISM [arm64-darwin25]

### Operating System

macOS (Apple Silicon)

### Bug Description

- rustc 1.92.0 (ded5c06cf 2025-12-08)

## Ruby 3.4.5

- rubygems: 3.6.9
- bundler: 2.5.23

In the case, `gem install rfmt` works fine.

## Ruby 3.4.8

- rubygems: 4.0.3
- bundler: 4.0.3

In the case, you need to perform `brew install coreutils` before running `gem install rfmt`, which means the installation depends on coreutils such as `gmkdir`. Or you will receive the following error:

<details style="cursor: pointer"><summary>(click to expand)</summary>

```sh
gem install rfmt
Fetching rfmt-1.4.1.gem
Building native extensions. This could take a while...
ERROR:  Error installing rfmt:
	ERROR: Failed to build gem native extension.

    current directory: /Users/hachi8833/.anyenv/envs/rbenv/versions/3.4.8/lib/ruby/gems/3.4.0/gems/rfmt-1.4.1/ext/rfmt
/Users/hachi8833/.anyenv/envs/rbenv/versions/3.4.8/bin/ruby extconf.rb
checking for clang... yes
checking for clang++... yes
checking for llvm-ar... no
checking for cargo... yes
checking for install_name_tool... yes

current directory: /Users/hachi8833/.anyenv/envs/rbenv/versions/3.4.8/lib/ruby/gems/3.4.0/gems/rfmt-1.4.1/ext/rfmt
make -j9 DESTDIR\= sitearchdir\=./.gem.20260120-45513-4cd2j8 sitelibdir\=./.gem.20260120-45513-4cd2j8 clean

current directory: /Users/hachi8833/.anyenv/envs/rbenv/versions/3.4.8/lib/ruby/gems/3.4.0/gems/rfmt-1.4.1/ext/rfmt
make -j9 DESTDIR\= sitearchdir\=./.gem.20260120-45513-4cd2j8 sitelibdir\=./.gem.20260120-45513-4cd2j8
generating target/aarch64-apple-darwin/release/librfmt.dylib (release)
cargo rustc  --manifest-path ./Cargo.toml --target aarch64-apple-darwin --target-dir target --lib --profile release -- -C linker=clang -L native=/Users/hachi8833/.anyenv/envs/rbenv/versions/3.4.8/lib -L native=/opt/homebrew/lib -L native=/opt/homebrew/Cellar/gmp/6.3.0/lib -C link-arg=-Wl,-undefined,dynamic_lookup -l pthread
   Compiling proc-macro2 v1.0.105
   Compiling quote v1.0.43
   Compiling unicode-ident v1.0.22
   Compiling memchr v2.7.6
   Compiling libc v0.2.179
   Compiling cfg-if v1.0.4
   Compiling serde_core v1.0.228
   Compiling serde v1.0.228
   Compiling glob v0.3.3
   Compiling crunchy v0.2.4
   Compiling clang-sys v1.8.1
   Compiling aho-corasick v1.1.4
   Compiling minimal-lexical v0.2.1
   Compiling version_check v0.9.5
   Compiling regex-syntax v0.8.8
   Compiling zerocopy v0.8.31
   Compiling ahash v0.8.12
   Compiling nom v7.1.3
   Compiling regex-automata v0.4.13
   Compiling libloading v0.8.9
   Compiling bindgen v0.69.5
   Compiling tiny-keccak v2.0.2
   Compiling syn v2.0.113
   Compiling allocator-api2 v0.2.21
   Compiling either v1.15.0
   Compiling itertools v0.12.1
   Compiling cexpr v0.6.0
   Compiling regex v1.12.2
   Compiling once_cell v1.21.3
   Compiling rustc-hash v1.1.0
   Compiling equivalent v1.0.2
   Compiling bitflags v2.10.0
   Compiling lazy_static v1.5.0
   Compiling lazycell v1.3.0
   Compiling shlex v1.3.0
   Compiling getrandom v0.2.16
   Compiling ucd-trie v0.1.7
   Compiling shell-words v1.1.1
   Compiling crossbeam-utils v0.8.21
   Compiling pest v2.8.5
   Compiling const-random-macro v0.1.16
   Compiling utf8parse v0.2.2
   Compiling hashbrown v0.16.1
   Compiling hashbrown v0.14.5
   Compiling autocfg v1.5.0
   Compiling num-traits v0.2.19
   Compiling indexmap v2.12.1
   Compiling pest_meta v2.8.5
   Compiling serde_derive v1.0.228
   Compiling const-random v0.1.18
   Compiling anstyle-parse v0.2.7
   Compiling is_terminal_polyfill v1.70.2
   Compiling zmij v1.0.12
   Compiling anstyle v1.0.13
   Compiling colorchoice v1.0.4
   Compiling anstyle-query v1.1.5
   Compiling pest_generator v2.8.5
   Compiling anstream v0.6.21
   Compiling dlv-list v0.5.2
   Compiling crossbeam-epoch v0.9.18
   Compiling rayon-core v1.13.0
   Compiling toml_write v0.1.2
   Compiling serde_json v1.0.149
   Compiling log v0.4.29
   Compiling itoa v1.0.17
   Compiling rb-sys-build v0.9.124
   Compiling rb-sys-env v0.1.2
   Compiling winnow v0.7.14
   Compiling magnus v0.6.4
   Compiling crossbeam-deque v0.8.6
   Compiling pest_derive v2.8.5
   Compiling ordered-multimap v0.7.3
   Compiling hashlink v0.8.4
   Compiling encoding_rs v0.8.35
   Compiling rb-sys v0.9.124
   Compiling serde_spanned v0.6.9
   Compiling toml_datetime v0.6.11
   Compiling arraydeque v0.5.1
   Compiling clap_lex v0.7.6
   Compiling heck v0.5.0
   Compiling toml_edit v0.22.27
   Compiling base64 v0.21.7
   Compiling strsim v0.11.1
   Compiling unicode-segmentation v1.12.0
   Compiling foldhash v0.1.5
   Compiling anyhow v1.0.100
   Compiling option-ext v0.2.0
   Compiling thiserror v1.0.69
   Compiling dirs-sys v0.4.1
   Compiling convert_case v0.6.0
   Compiling hashbrown v0.15.5
   Compiling yaml-rust2 v0.8.1
   Compiling clap_builder v4.5.54
   Compiling toml v0.8.23
   Compiling ron v0.8.1
   Compiling clap_derive v4.5.49
   Compiling json5 v0.4.1
   Compiling env_filter v0.1.4
   Compiling rust-ini v0.20.0
   Compiling rmp v0.8.15
   Compiling thiserror-impl v1.0.69
   Compiling magnus-macros v0.6.0
   Compiling async-trait v0.1.89
   Compiling bstr v1.12.1
   Compiling unsafe-libyaml v0.2.11
   Compiling jiff v0.2.18
   Compiling ryu v1.0.22
   Compiling pathdiff v0.2.3
   Compiling seq-macro v0.3.6
   Compiling rayon v1.11.0
   Compiling config v0.14.1
   Compiling serde_yaml v0.9.34+deprecated
   Compiling globset v0.4.18
   Compiling rmp-serde v1.3.1
   Compiling clap v4.5.54
   Compiling lru v0.12.5
   Compiling dirs v5.0.1
   Compiling num_cpus v1.17.0
   Compiling env_logger v0.11.8
   Compiling rfmt v1.4.1 (/Users/hachi8833/.anyenv/envs/rbenv/versions/3.4.8/lib/ruby/gems/3.4.0/gems/rfmt-1.4.1/ext/rfmt)
    Finished `release` profile [optimized] target(s) in 23.96s

current directory: /Users/hachi8833/.anyenv/envs/rbenv/versions/3.4.8/lib/ruby/gems/3.4.0/gems/rfmt-1.4.1/ext/rfmt
make -j9 DESTDIR\= sitearchdir\=./.gem.20260120-45513-4cd2j8 sitelibdir\=./.gem.20260120-45513-4cd2j8 install
make: /opt/homebrew/bin/gmkdir: No such file or directory
make: *** [.sitearchdir.time] Error 1
make: *** Waiting for unfinished jobs....
generating target/aarch64-apple-darwin/release/librfmt.dylib (release)
cargo rustc  --manifest-path ./Cargo.toml --target aarch64-apple-darwin --target-dir target --lib --profile release -- -C linker=clang -L native=/Users/hachi8833/.anyenv/envs/rbenv/versions/3.4.8/lib -L native=/opt/homebrew/lib -L native=/opt/homebrew/Cellar/gmp/6.3.0/lib -C link-arg=-Wl,-undefined,dynamic_lookup -l pthread
    Finished `release` profile [optimized] target(s) in 0.31s

make install failed, exit code 2

Gem files will remain installed in /Users/hachi8833/.anyenv/envs/rbenv/versions/3.4.8/lib/ruby/gems/3.4.0/gems/rfmt-1.4.1 for inspection.
Results logged to /Users/hachi8833/.anyenv/envs/rbenv/versions/3.4.8/lib/ruby/gems/3.4.0/extensions/arm64-darwin-25/3.4.0-static/rfmt-1.4.1/gem_make.out
```

</details>

## Ruby 4.0.1

- rubygems: 4.0.3
- bundler: 4.0.3

In the case, the following different error occurs, which looks like this might be affected by some recent changes on RTypedData struct:

<details style="cursor: pointer"><summary>(click to expand)</summary>

```sh
gem install rfmt
Building native extensions. This could take a while...
ERROR:  Error installing rfmt:
	ERROR: Failed to build gem native extension.

    current directory: /Users/hachi8833/.anyenv/envs/rbenv/versions/4.0.1/lib/ruby/gems/4.0.0/gems/rfmt-1.4.1/ext/rfmt
/Users/hachi8833/.anyenv/envs/rbenv/versions/4.0.1/bin/ruby extconf.rb
checking for clang... yes
checking for clang++... yes
checking for ar... yes
checking for cargo... yes
checking for install_name_tool... yes

current directory: /Users/hachi8833/.anyenv/envs/rbenv/versions/4.0.1/lib/ruby/gems/4.0.0/gems/rfmt-1.4.1/ext/rfmt
make -j9 DESTDIR\= sitearchdir\=./.gem.20260120-38740-vdqjwv sitelibdir\=./.gem.20260120-38740-vdqjwv clean

current directory: /Users/hachi8833/.anyenv/envs/rbenv/versions/4.0.1/lib/ruby/gems/4.0.0/gems/rfmt-1.4.1/ext/rfmt
make -j9 DESTDIR\= sitearchdir\=./.gem.20260120-38740-vdqjwv sitelibdir\=./.gem.20260120-38740-vdqjwv
generating target/aarch64-apple-darwin/release/librfmt.dylib (release)
cargo rustc  --manifest-path ./Cargo.toml --target aarch64-apple-darwin --target-dir target --lib --profile release -- -C linker=clang -L native=/Users/hachi8833/.anyenv/envs/rbenv/versions/4.0.1/lib -L native=/opt/homebrew/lib -L native=/opt/homebrew/Cellar/gmp/6.3.0/lib -C link-arg=-Wl,-undefined,dynamic_lookup -l pthread
   Compiling proc-macro2 v1.0.105
   Compiling unicode-ident v1.0.22
   Compiling quote v1.0.43
   Compiling memchr v2.7.6
   Compiling libc v0.2.179
   Compiling cfg-if v1.0.4
   Compiling serde_core v1.0.228
   Compiling glob v0.3.3
   Compiling serde v1.0.228
   Compiling regex-syntax v0.8.8
   Compiling clang-sys v1.8.1
   Compiling aho-corasick v1.1.4
   Compiling crunchy v0.2.4
   Compiling minimal-lexical v0.2.1
   Compiling version_check v0.9.5
   Compiling zerocopy v0.8.31
   Compiling nom v7.1.3
   Compiling ahash v0.8.12
   Compiling regex-automata v0.4.13
   Compiling libloading v0.8.9
   Compiling bindgen v0.69.5
   Compiling either v1.15.0
   Compiling allocator-api2 v0.2.21
   Compiling tiny-keccak v2.0.2
   Compiling itertools v0.12.1
   Compiling cexpr v0.6.0
   Compiling syn v2.0.113
   Compiling equivalent v1.0.2
   Compiling rustc-hash v1.1.0
   Compiling shlex v1.3.0
   Compiling regex v1.12.2
   Compiling bitflags v2.10.0
   Compiling once_cell v1.21.3
   Compiling lazy_static v1.5.0
   Compiling lazycell v1.3.0
   Compiling getrandom v0.2.16
   Compiling ucd-trie v0.1.7
   Compiling shell-words v1.1.1
   Compiling crossbeam-utils v0.8.21
   Compiling pest v2.8.5
   Compiling utf8parse v0.2.2
   Compiling const-random-macro v0.1.16
   Compiling autocfg v1.5.0
   Compiling hashbrown v0.14.5
   Compiling hashbrown v0.16.1
   Compiling num-traits v0.2.19
   Compiling pest_meta v2.8.5
   Compiling const-random v0.1.18
   Compiling indexmap v2.12.1
   Compiling anstyle-parse v0.2.7
   Compiling colorchoice v1.0.4
   Compiling zmij v1.0.12
   Compiling is_terminal_polyfill v1.70.2
   Compiling anstyle v1.0.13
   Compiling anstyle-query v1.1.5
   Compiling crossbeam-epoch v0.9.18
   Compiling anstream v0.6.21
   Compiling pest_generator v2.8.5
   Compiling dlv-list v0.5.2
   Compiling winnow v0.7.14
   Compiling serde_json v1.0.149
   Compiling log v0.4.29
   Compiling toml_write v0.1.2
   Compiling itoa v1.0.17
   Compiling rayon-core v1.13.0
   Compiling serde_derive v1.0.228
   Compiling rb-sys-env v0.1.2
   Compiling pest_derive v2.8.5
   Compiling magnus v0.6.4
   Compiling rb-sys-build v0.9.124
   Compiling ordered-multimap v0.7.3
   Compiling crossbeam-deque v0.8.6
   Compiling hashlink v0.8.4
   Compiling encoding_rs v0.8.35
   Compiling heck v0.5.0
   Compiling arraydeque v0.5.1
   Compiling thiserror v1.0.69
   Compiling clap_lex v0.7.6
   Compiling base64 v0.21.7
   Compiling anyhow v1.0.100
   Compiling strsim v0.11.1
   Compiling unicode-segmentation v1.12.0
   Compiling rb-sys v0.9.124
   Compiling option-ext v0.2.0
   Compiling foldhash v0.1.5
   Compiling hashbrown v0.15.5
   Compiling toml_datetime v0.6.11
   Compiling serde_spanned v0.6.9
   Compiling ron v0.8.1
   Compiling json5 v0.4.1
   Compiling dirs-sys v0.4.1
   Compiling toml_edit v0.22.27
   Compiling convert_case v0.6.0
   Compiling yaml-rust2 v0.8.1
   Compiling clap_builder v4.5.54
   Compiling toml v0.8.23
   Compiling clap_derive v4.5.49
   Compiling rust-ini v0.20.0
   Compiling rmp v0.8.15
   Compiling env_filter v0.1.4
   Compiling async-trait v0.1.89
   Compiling thiserror-impl v1.0.69
   Compiling magnus-macros v0.6.0
   Compiling bstr v1.12.1
   Compiling pathdiff v0.2.3
   Compiling seq-macro v0.3.6
   Compiling jiff v0.2.18
   Compiling unsafe-libyaml v0.2.11
   Compiling ryu v1.0.22
   Compiling rayon v1.11.0
   Compiling globset v0.4.18
   Compiling serde_yaml v0.9.34+deprecated
error[E0609]: no field `typed_flag` on type `&rb_sys::RTypedData`
   --> /Users/hachi8833/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/magnus-0.6.4/src/r_typed_data.rs:200:42
    |
200 |                     (typed_data.as_ref().typed_flag == 1)
    |                                          ^^^^^^^^^^ unknown field
    |
    = note: available fields are: `basic`, `fields_obj`, `type_`, `data`

   Compiling config v0.14.1
For more information about this error, try `rustc --explain E0609`.
error: could not compile `magnus` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
make: *** [target/aarch64-apple-darwin/release/librfmt.dylib] Error 101

make failed, exit code 2

Gem files will remain installed in /Users/hachi8833/.anyenv/envs/rbenv/versions/4.0.1/lib/ruby/gems/4.0.0/gems/rfmt-1.4.1 for inspection.
Results logged to /Users/hachi8833/.anyenv/envs/rbenv/versions/4.0.1/lib/ruby/gems/4.0.0/extensions/arm64-darwin-25/4.0.0-static/rfmt-1.4.1/gem_make.out
```

</details>
<br>

### Expected Behavior

`gem install rfmt` should work in Ruby 3.4.8 and 4.0.1.

### Actual Behavior

`gem install rfmt` causes errors in Ruby 3.4.8 and 4.0.1 as above.

### Reproduction Code

```ruby
n/a
```

### Error Output

```shell

```

### Configuration (if applicable)

```yaml

```
